In [1]:
#article: https://machinelearningmastery.com/upsampling-and-transpose-convolution-layers-for-generative-adversarial-networks/
#using upsampling 2D layer 
from numpy import asarray 
from keras.models import Sequential 
from keras.layers import UpSampling2D

X = asarray([[1, 2], [3, 4]])

In [2]:
print(X)

[[1 2]
 [3 4]]


In [4]:
X = X.reshape((1,2,2,1))
model = Sequential()
model.add(UpSampling2D(input_shape=(2,2,1)))
model.summary()

yhat = model.predict(X)
yhat = yhat.reshape((4,4))
print(yhat)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [5]:
#Simple generator model with the Upsampling 2D layer 
from keras.models import Sequential 
from keras.layers import Dense 
from keras.layers import Reshape 
from keras.layers import UpSampling2D
from keras.layers import Conv2D 
model = Sequential()

model.add(Dense(128 * 5 * 5, input_dim = 100))

model.add(Reshape((5, 5, 128)))

model.add(UpSampling2D())

model.add((Conv2D(1, (3,3), padding='same')))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_2 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


In [2]:
#Conv2D transpose layer 
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose

X = asarray([[1, 2],
 [3, 4]])

print(X)

X = X.reshape((1, 2, 2, 1))

model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))

model.summary()

weights = [asarray([[[[1]]]]), asarray([0])]

model.set_weights(weights)

yhat = model.predict(X)

yhat = yhat.reshape((4, 4))

print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_1 (Conv2DTr (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


In [5]:
#Simple generator model with conv2D transpose 

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import Conv2DTranspose
from keras.layers import Conv2D

model = Sequential()

model.add(Dense(128 * 5 * 5, input_dim=100))

model.add(Reshape((5, 5, 128)))

model.add(Conv2DTranspose(1, (3,3), strides=(2,2), padding='same'))

model.summary()



Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_3 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
